# Generated by Django 5.2.6 on 2025-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('INVITE', 'Invités'), ('RETREAT', 'Retraite')], max_length=20),
        ),
    ]
