# Generated by Django 5.2.6 on 2025-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
