# Generated by Django 5.2.6 on 2025-09-21 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilletGlobalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglement_pdf', models.FileField(blank=True, null=True, upload_to='billets_globaux/')),
                ('objets_pdf', models.FileField(blank=True, null=True, upload_to='billets_globaux/')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_active', models.BooleanField(default=True, verbose_name='Ouverture des inscriptions')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance (bloque tout)')),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('message', models.TextField(verbose_name='Témoignage')),
                ('color', models.CharField(choices=[('rose', 'Rose'), ('bleu', 'Bleu'), ('jaune', 'Jaune'), ('vert', 'Vert'), ('violet', 'Violet'), ('gris', 'Gris')], default='rose', max_length=12, verbose_name='Couleur')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateliers', to='events.event')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ateliers_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True)),
                ('capacite', models.PositiveIntegerField(default=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='events.event')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chambres_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('connexion', 'Connexion'), ('access', 'Accès page'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('param', 'Paramétrage'), ('other', 'Autre')], default='other', max_length=30)),
                ('action', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_participant', models.CharField(choices=[('Participant', 'Participant'), ('ouvrier', 'Ouvrier de la jeunesse')], default='Participant', max_length=20, verbose_name='Type de participant')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/photos/')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_urgence', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('present', models.BooleanField(default=False)),
                ('date_presence', models.DateTimeField(blank=True, null=True)),
                ('billet_envoye', models.BooleanField(default=False)),
                ('billet_envoye_email', models.BooleanField(default=False)),
                ('billet_envoye_whatsapp', models.BooleanField(default=False)),
                ('billet_pdf', models.FileField(blank=True, null=True, upload_to='billets/')),
                ('date_billet_envoye', models.DateTimeField(blank=True, null=True)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='preuves_paiement/')),
                ('paiement_valide', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code reprenant nom, prénom, chambre et atelier', null=True, upload_to='qr_codes/')),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retreat.atelier')),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retreat.chambre')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants_owned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('acces_billets', 'Accès à la gestion des billets'), ('acces_paiements', 'Accès à la gestion des paiements'), ('acces_groupes', 'Accès à la gestion des groupes et ateliers'), ('acces_scan', 'Accès au scan QR code'), ('acces_participants', 'Accès à la gestion des participants'), ('acces_presence', 'Accès à la liste des présences'), ('acces_parametrage', 'Accès au paramétrage')],
                'unique_together': {('event', 'nom', 'prenom')},
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retreat.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables_directs', to='retreat.atelier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Responsable_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='chambres', to='retreat.responsable'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='ateliers', to='retreat.responsable'),
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('event', 'nom', 'sexe')},
        ),
        migrations.AlterUniqueTogether(
            name='atelier',
            unique_together={('event', 'numero')},
        ),
    ]
