# Generated by Django 5.2.6 on 2025-09-23 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('retreat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atelier',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='retreat.participant'),
        ),
        migrations.AddIndex(
            model_name='atelier',
            index=models.Index(fields=['event', 'numero'], name='retreat_ate_event_i_479326_idx'),
        ),
        migrations.AddIndex(
            model_name='chambre',
            index=models.Index(fields=['event', 'sexe'], name='retreat_cha_event_i_f51db4_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['event', 'nom', 'prenom'], name='retreat_par_event_i_467b7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='atelier',
            constraint=models.UniqueConstraint(fields=('event', 'numero'), name='uniq_atelier_event_numero'),
        ),
        migrations.AddConstraint(
            model_name='chambre',
            constraint=models.UniqueConstraint(fields=('event', 'nom', 'sexe'), name='uniq_chambre_event_nom_sexe'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'nom', 'prenom'), name='uniq_participant_event_nom_prenom'),
        ),
    ]
