"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
http://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
http://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    # Fallback si python-dotenv n'est pas install�: on d�finit un stub pour ne pas casser l'import.
    def load_dotenv(*args, **kwargs):
        return None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")



DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Quick-start development settings - unsuitable for production
# See http://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-key-change-me") or "dev-insecure-key-change-me"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# En dev, on force le HTTP simple (pas de redirection vers HTTPS)
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps projet
    
     # Sites (requis par allauth)
    'django.contrib.sites',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  
    'allauth.mfa',             

       # Ton projet
    'core', 'events', 'guests', 'retreat', 'scanner', 'dash', 
]
INSTALLED_APPS += [
    'crispy_forms',
    'crispy_bootstrap5',
    'django_extensions'
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


SITE_ID = 1  # on mettra à jour le domaine en admin plus tard
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',      # Django
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',   # <= AJOUT OBLIGATOIRE (allauth)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# http://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# http://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# http://docs.djangoproject.com/en/5.2/topics/i18n/



LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Kinshasa' # adapte si besoin

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# http://docs.djangoproject.com/en/5.2/howto/static-files/



STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'# Paramètres compte (adapte à ton besoin)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"     # ou smtp.gmail.com, mailgun, etc.
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ebenndombi99@gmail.com'            # dépend du provider
EMAIL_HOST_PASSWORD = 'kree pfxs hayb hdtj'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = 'account_login'            # allauth
LOGIN_REDIRECT_URL = '/dashboard/'     # où aller après login
LOGOUT_REDIRECT_URL = '/'

# MFA (perso)
MFA_SUPPORTED_TYPES = ["recovery_codes", "totp"]  # on ajoutera "webauthn" plus tard
MFA_ENFORCE_FOR_SUPERUSERS = True  # optionnel, force pour superusers
# Tu peux plus tard coder une règle pour imposer MFA aux rôles OWNER/STAFF
# http://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
