# Generated by Django 5.2.6 on 2025-10-08 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='table',
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('nombre_de_places', models.PositiveIntegerField()),
                ('event', models.ForeignKey(blank=True, help_text="Doit être un Event de type 'guests'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tele', models.CharField(blank=True, default='', max_length=15)),
                ('code', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('present', models.BooleanField(default=False)),
                ('scanned', models.BooleanField(default=False)),
                ('date_scanned', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('opened', 'Ouverte'), ('confirmed', 'Confirmée'), ('declined', 'Déclinée'), ('bounced', 'Email en erreur')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event', models.ForeignKey(blank=True, help_text="Doit être un Event de type 'guests'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='guests.table')),
            ],
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['event', 'numero'], name='guests_tabl_event_i_a729d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('event', 'numero')},
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['event', 'nom', 'prenom'], name='guests_invi_event_i_882096_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['code'], name='guests_invi_code_e9b6f2_idx'),
        ),
    ]
