# Generated by Django 5.2.6 on 2025-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guest_event_remove_guest_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
