# Generated by Django 5.2.6 on 2025-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_merge_0003_alter_invite_email_0003_invite_couple_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='nom',
            field=models.CharField(blank=True, help_text="Ex: 'Table d'Honneur', 'Les Cousins'...", max_length=100, null=True),
        ),
    ]
