# Generated by Django 5.2.6 on 2025-12-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_table_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond (Hex).', max_length=7),
        ),
    ]
