# Generated by Django 5.2.6 on 2025-12-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_table_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='x_pos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='table',
            name='y_pos',
            field=models.FloatField(default=0.0),
        ),
    ]
