# Generated by Django 5.2.6 on 2025-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_table_x_pos_table_y_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('round', 'Ronde'), ('square', 'Carrée'), ('rectangle', 'Rectangulaire')], default='round', max_length=10),
        ),
    ]
