# Generated by Django 5.2.6 on 2026-04-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location_url_event_theme_alter_event_venue_and_more'),
        ('guests', '0008_table_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, default='')),
                ('css_content', models.TextField(blank=True, default='')),
                ('components_data', models.TextField(blank=True, default='[]', help_text='Données JSON structurelles (GrapesJS)')),
                ('styles_data', models.TextField(blank=True, default='[]', help_text='Styles JSON (GrapesJS)')),
                ('has_envelope_animation', models.BooleanField(default=True, help_text="Activer l'animation 3D de l'enveloppe à l'ouverture")),
                ('music_url', models.URLField(blank=True, help_text='Lien vers une musique de fond (Optionnel)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_template', to='events.event')),
            ],
        ),
    ]
